/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cowin;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tejveeraa
 */
public class registration extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        fvaccine = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fmobile = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        fage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fadhar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        faddress = new javax.swing.JTextArea();
        fmale = new javax.swing.JRadioButton();
        ffemale = new javax.swing.JRadioButton();
        fother = new javax.swing.JRadioButton();
        fcovax = new javax.swing.JRadioButton();
        fcosh = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apisero Vaccine Registration");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        fvaccine.setBackground(new java.awt.Color(204, 255, 204));
        fvaccine.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registration", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        fvaccine.setForeground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("Mobile Number");

        jLabel3.setText("Name");

        jLabel4.setText("Age");

        fage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fageActionPerformed(evt);
            }
        });

        jLabel5.setText("Adhar Number");

        jLabel6.setText("Gender");

        jLabel7.setText("Address");

        jLabel8.setText("Vaccine Name");

        faddress.setColumns(20);
        faddress.setRows(5);
        jScrollPane1.setViewportView(faddress);

        fmale.setText("Male");
        fmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmaleActionPerformed(evt);
            }
        });

        ffemale.setText("Female");
        ffemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffemaleActionPerformed(evt);
            }
        });

        fother.setText("Other");
        fother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotherActionPerformed(evt);
            }
        });

        fcovax.setText("Covaxin");
        fcovax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcovaxActionPerformed(evt);
            }
        });

        fcosh.setText("Covishield");
        fcosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcoshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fvaccineLayout = new javax.swing.GroupLayout(fvaccine);
        fvaccine.setLayout(fvaccineLayout);
        fvaccineLayout.setHorizontalGroup(
            fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fvaccineLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fvaccineLayout.createSequentialGroup()
                        .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fvaccineLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(fmale)
                                .addGap(10, 10, 10)
                                .addComponent(ffemale)
                                .addGap(18, 18, 18)
                                .addComponent(fother)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fvaccineLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(fvaccineLayout.createSequentialGroup()
                                        .addComponent(fcovax)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fcosh)
                                        .addGap(17, 17, 17))))))
                    .addGroup(fvaccineLayout.createSequentialGroup()
                        .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(89, 89, 89)
                        .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fname)
                            .addComponent(fmobile)
                            .addComponent(fage)
                            .addComponent(fadhar))))
                .addGap(25, 25, 25))
        );
        fvaccineLayout.setVerticalGroup(
            fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fvaccineLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(fage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fmale)
                    .addComponent(ffemale)
                    .addComponent(fother))
                .addGap(18, 18, 18)
                .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(fvaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fcovax)
                        .addComponent(fcosh)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fvaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 164, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fvaccine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        // TODO add your handling code here:
        String mobile= fmobile.getText();
       // long mobile=Long.parseLong(tmobile);
        String name= fname.getText();
        String tage= fage.getText();
        int age=Integer.parseInt(tage);
        long adhar= Long.parseLong(fadhar.getText());
        String gender = null;
        String address= faddress.getText();
        String vaccine = null ;
        if(fmale.isSelected()){
            gender="Male";
        }
        if(ffemale.isSelected())
        {
            gender="Female";
        }
        if(fother.isSelected())
        {
            gender="Other";
        }
        if(fcovax.isSelected())
            vaccine="Covaxin";
        if(fcosh.isSelected())
            vaccine="Covishield";
       
          try {
			
			Class.forName("com.mysql.cj.jdbc.Driver"); // create connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cowin", "root", "");
           String qry="INSERT INTO user (`mobile`, `name`, `age`, `adhar`, `gender`, `address`, `vaccine`) "
                    + "VALUES ('"+mobile+"','"+name+"',"+age+","+adhar+",'"+ gender+"','"+address+"','"+vaccine+"');" ;
            
            PreparedStatement stmt = con.prepareStatement(qry);
               /* stmt.setLong(1,mobile);
                stmt.setString(2, name);
                stmt.setInt(3, age);
                stmt.setLong(4,adhar );
                stmt.setString(5,gender);
                stmt.setString(6,address);
                stmt.setString(7,vaccine); */
                
               stmt.executeUpdate();
               
               JOptionPane.showMessageDialog(this,"Record is Added !!");
                
                fmobile.setText("");
                fname.setText("");
                fage.setText("");
                fadhar.setText("");
                
                fmale.setSelected(false);
                 ffemale.setSelected(false);
                  fother.setSelected(false);
                faddress.setText("");
              
                fcovax.setSelected(false);
                fcosh.setSelected(false);
                
                fmobile.requestFocus();
                
            
		}
	catch (ClassNotFoundException | SQLException ex) {
			Logger.getLogger(registration.class.getName()).log(Level.SEVERE,null,ex);
			}
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
public void close(){
        WindowEvent closeWindow =new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close();
        index idx= new index();
        idx.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmaleActionPerformed
        // TODO add your handling code here:
        
        if(fmale.isSelected()){
            ffemale.setSelected(false);
            fother.setSelected(false);
        }
    }//GEN-LAST:event_fmaleActionPerformed

    private void ffemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffemaleActionPerformed
        // TODO add your handling code here:
        
        if(ffemale.isSelected()){
            fmale.setSelected(false);
            fother.setSelected(false);
        }
    }//GEN-LAST:event_ffemaleActionPerformed

    private void fotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotherActionPerformed
        // TODO add your handling code here:
        if(fother.isSelected()){
            ffemale.setSelected(false);
            fmale.setSelected(false);
        }
    }//GEN-LAST:event_fotherActionPerformed

    private void fcovaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcovaxActionPerformed
        // TODO add your handling code here:
        if(fcovax.isSelected())
            fcosh.setSelected(false);
    }//GEN-LAST:event_fcovaxActionPerformed

    private void fcoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcoshActionPerformed
        // TODO add your handling code here:
        
        if(fcosh.isSelected())
            fcovax.setSelected(false);
    }//GEN-LAST:event_fcoshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextArea faddress;
    private javax.swing.JTextField fadhar;
    private javax.swing.JTextField fage;
    private javax.swing.JRadioButton fcosh;
    private javax.swing.JRadioButton fcovax;
    private javax.swing.JRadioButton ffemale;
    private javax.swing.JRadioButton fmale;
    private javax.swing.JTextField fmobile;
    private javax.swing.JTextField fname;
    private javax.swing.JRadioButton fother;
    private javax.swing.JPanel fvaccine;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
